### ISSUE TITLE
NavController Lifecycleevents-table

### ISSUE THREAD

**Issue by Blackscr33n** [driftyco/ionic-site#901] opened 2016-11-25 12:14 UTC
Hey Community!

I found a layout-problem here at the table for the Lifecycleevents:
http://ionicframework.com/docs/v2/api/navigation/NavController/
![screen](https://cloud.githubusercontent.com/assets/6410789/20625053/0619cf14-b311-11e6-981a-d208a74c9724.png)

Greets,
Bernhard

**Comment by ZiFFeL1992** [comment] 2017-01-04 11:15
I was about to post this as well.

**Comment by brandyscarney** [comment] 2017-01-04 15:34
Thanks! Closing as a duplicate of #885. :Smile:

**Closed by brandyscarney** 2017-01-04 15:34 UTC
