### ISSUE TITLE
Define issues/potential gotchas with ionic serve

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-site#688] opened 2016-07-08 21:08 UTC
(Based on discussions here: https://www.thepolyglotdeveloper.com/2016/02/why-you-should-not-use-ionic-serve-for-hybrid-apps/)

In the docs for ionic serve, some time should be spent talking about potential gotchas/issues with using ionic serve. While obvious to people experienced with hybrid mobile developers, a new developer may not realize what will and will not work when using ionic serve.

**Comment by nraboy** [comment] 2016-07-08 21:09
Well said

**Comment by mhartington** [comment] 2016-07-08 21:31
Much of this should be resolved with devs using plugins from ionic native.
In cases like this, when they try to use native plugins and there is no cordova around, such as running `ionic serve`, it will let them know what the issue is.

```
[Warning] Native: tried calling StatusBar.styleDefault, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator (app.bundle.js, line 83388)
```

This has already helped quite a bit  in V2 and will help in V1 as we migrate it over to ionic-native.
Sure there are going to be cases where devs are trying to use plugins ionic native doesn't support, but you pick your battle `¯\_(ツ)_/¯`


That being said, we can put something together to address this.

**Comment by nraboy** [comment] 2016-07-08 21:33
Ionic Native and ngCordova is only a fraction of the plugin ecosystem.  People have already and will continue to run into these issues on both Ionic 2 and Ionic 1.  You should update the documentation rather than saying "pick your battle".

**Comment by danbucholtz** [comment] 2016-07-08 21:40
@nraboy, what would you like to see?  You're a consumer of the docs, so I'd like to make them more user friendly.

Ionic 2 will support Electron, Cordova, Mobile Web and Desktop Web, so each platform should be tested using that specific platform.  `ionic serve` is great for getting the look-and-feel down, but each platform has it's own APIs for "native" functionality like persisting files, etc.  We could do a better job of articulating this.  Any ideas?

Thanks,
Dan

**Comment by mhartington** [comment] 2016-07-08 21:41
>That being said, we can put something together to address this.

As stated, notes will be added.

**Comment by nraboy** [comment] 2016-07-08 21:45
Yes, I see that, but when I see things like this:

> Sure there are going to be cases where devs are trying to use plugins ionic native doesn't support, but you pick your battle ¯\_(ツ)_/¯

That tells me you guys don't truly care about the success of your users.  Maybe that's not the case, but that is certainly what I'm interpreting.

**Comment by mhartington** [comment] 2016-07-08 22:08
@cfjedimaster wrote a bit and added it to our FAQ. 

https://github.com/driftyco/ionic-site/commit/2e3dd0753a6146b0e2ed148891e6e4bd883221e3

**Closed by mhartington** 2016-07-08 22:08 UTC

**Comment by nraboy** [comment] 2016-07-08 22:56
Looks good, but I'd like to recommend including an example of this obscure warning.  Maybe something like this:

```
TypeError: Cannot read property 'toast' of undefined
    at Object.show (http://localhost:8100/js/ng-cordova.min.js:9:15751)
    at Scope.$scope.showToast (http://localhost:8100/js/app.js:23:23)
    at $parseFunctionCall (http://localhost:8100/lib/ionic/js/ionic.bundle.js:20124:18)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:50863:9
    at Scope.$eval (http://localhost:8100/lib/ionic/js/ionic.bundle.js:22178:28)
    at Scope.$apply (http://localhost:8100/lib/ionic/js/ionic.bundle.js:22276:23)
    at HTMLButtonElement.<anonymous> (http://localhost:8100/lib/ionic/js/ionic.bundle.js:50862:13)
    at HTMLButtonElement.eventHandler (http://localhost:8100/lib/ionic/js/ionic.bundle.js:10823:21)
    at triggerMouseEvent (http://localhost:8100/lib/ionic/js/ionic.bundle.js:2811:7)
    at tapClick (http://localhost:8100/lib/ionic/js/ionic.bundle.js:2800:3)
```

Highlighting this line:

```
TypeError: Cannot read property 'toast' of undefined
```

You're on the right track though.
