### ISSUE TITLE
Sass variable table overlaps the preview demos

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-site#1019] opened 2017-03-15 19:36 UTC
![screen shot 2017-03-15 at 3 34 33 pm](https://cloud.githubusercontent.com/assets/2835826/23967384/193fc596-0995-11e7-97a7-798af55446d2.png)

Seems the sass variable table is overlapping the device preview.

**Comment by brandyscarney** [comment] 2017-03-15 20:18
Closing as a duplicate of https://github.com/driftyco/ionic-site/issues/867

**Closed by brandyscarney** 2017-03-15 20:18 UTC
